language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before-script:
- npm install --global gulp-cli
- npm install

script:
 - php artisan config:cache
 - gulp --production

notifications:
  slack: dynamictechnologies:QMzOTe9EFgTgVgO9Pyvx0c8e